#
#   Author: Rohith
#   Date: 2015-06-19 15:11:49 +0100 (Fri, 19 Jun 2015)
#
#  vim:ts=2:sw=2:et
#

apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: graphite
spec:
  replicas: 1
  selector:
    name: graphite
  template:
    metadata:
      labels:
        name: graphite
    spec:
      containers:
      - name: graphite
        image: hopsoft/graphite-statsd
        ports:
        - containerPort: 80
        - containerPort: 2003
        - containerPort: 8125
          protocol: udp
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 120
          timeoutSeconds: 3
