#
#   Author: Rohith
#   Date: 2015-06-20 21:57:30 +0100 (Sat, 20 Jun 2015)
#
#  vim:ts=2:sw=2:et
#

apiVersion: v1beta3
kind: Service
metadata:
  labels:
    name: mysql-master
  name: mysql-master
spec:
  portalIP: 10.101.100.77
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    name: mysql-master


