---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: gitlab-mysql1
  name: gitlab-mysql1
spec:
  clusterIP: 10.101.40.101
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
    - name: incremental-state
      port: 4444
      targetPort: 4444
    - name: replication
      port: 4567
      targetPort: 4567
    - name: full-state
      port: 4568
      targetPort: 4568
  selector:
    name: gitlab-mysql1
