#
#   Author: Rohith
#   Date: 2015-07-18 20:28:44 +0100 (Sat, 18 Jul 2015)
#
#  vim:ts=2:sw=2:et
#
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: gitlab-mysql2
spec:
  replicas: 1
  selector:
    name: gitlab-mysql2
  template:
    metadata:
      labels:
        name: gitlab-mysql2
    spec:
      containers:
      - name: mysql
        image: capttofu/percona_xtradb_cluster_5_6:latest
        ports:
          - containerPort: 3306
            hostPort: 3306
          - containerPort: 4444
            hostPort: 4444
          - containerPort: 4567
            hostPort: 4567
          - containerPort: 4568
            hostPort: 4568
        env:
          - name: GALERA_CLUSTER
            value: "true"
          - name: WSREP_SST_USER
            value: sst
          - name: WSREP_SST_PASSWORD
            value: sst
          - name: MYSQL_USER
            value: mysql
          - name: MYSQL_PASSWORD
            value: mysql
          - name: MYSQL_ROOT_PASSWORD
            value: c-krit
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      volumes:
        - name: data
          rbd:
            monitors:
              - 10.50.10.100:6789
              - 10.50.11.100:6789
              - 10.50.12.100:6789
            pool: rbd
            image: gitlab-mysql2
            user: admin
            secretRef:
              name: ceph-secret
            fsType: xfs
            readOnly: false
