#
#   Author: Rohith
#   Date: 2015-05-20 23:35:53 +0100 (Wed, 20 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: gitlab-redis
spec:
  replicas: 1
  selector:
    name: gitlab-redis
  template:
    metadata:
      labels:
        name: gitlab-redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "1"
