#
#   Author: Rohith
#   Date: 2015-05-20 23:36:09 +0100 (Wed, 20 May 2015)
#
#  vim:ts=2:sw=2:et
#
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: gitlab-mysql
spec:
  replicas: 1
  selector:
    name: gitlab-mysql
  template:
    metadata:
      labels:
        name: gitlab-mysql
    spec:
      containers:
      - name: gitlab-mysql
        image: tutum/mysql
        volumeMounts:
          - name: mysql
            mountPath: /var/lib/mysql
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_PASS
          value: dfdsmfk983w
      volumes:
        - name: mysql
          rbd:
            monitors:
              - 10.50.10.100:6789
              - 10.50.11.100:6789
              - 10.50.12.100:6789
            pool: rbd
            image: gitlab-mysql
            user: admin
            secretRef:
              name: ceph-secret
            fsType: xfs
            readOnly: false
