#
#   Author: Rohith
#   Date: 2015-05-20 23:36:09 +0100 (Wed, 20 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: gitlab-mysql
spec:
  replicas: 1
  selector:
    name: gitlab-mysql
  template:
    metadata:
      labels:
        name: gitlab-mysql
    spec:
      containers:
      - name: gitlab-mysql
        image: tutum/mysql
        volumeMounts:
          - name: mysql
            mountPath: /var/lib/mysql
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_PASS
          value: dfdsmfk983w
        - name: REPLICATION_MASTER
          value: "true"
        - name: REPLICATION_USER
          value: replication
        - name: REPLICATION_PASS
          value: d67as9f7sjhsdfsd
      volumes:
        - name: mysql
          rbd: 
            monitors: 
              - 10.250.1.53:6789
              - 10.250.1.54:6789
            pool: rbd
            image: gitlab-mysql
            user: admin
            keyring: /etc/ceph/ceph.client.admin.keyring
            fsType: xfs
            readOnly: false

