#
#   Author: Rohith
#   Date: 2015-05-20 23:36:07 +0100 (Wed, 20 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

apiVersion: v1
kind: Service
metadata:
  labels:
    name: gitlab-mysql
  name: gitlab-mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    name: gitlab-mysql
  clusterIP: 10.101.1.101

