#
#   Author: Rohith
#   Date: 2015-05-20 23:35:53 +0100 (Wed, 20 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

apiVersion: v1
kind: ReplicationController
metadata:
  name: gitlab-redis
spec:
  replicas: 1
  selector:
    name: gitlab-redis
  template:
    metadata:
      labels:
        name: gitlab-redis
      annotations:
        metrics: |
          - name: redis
            port: 9001
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
      - name: metrics
        image: 21zoo/redis_exporter
        args:
        - -web.listen-address=0.0.0.0:9001
        ports:
        - containerPort: 9001
