#
#   Author: Rohith
#   Date: 2015-05-20 23:35:59 +0100 (Wed, 20 May 2015)
#
#  vim:ts=2:sw=2:et
#
apiVersion: v1
kind: Service
metadata:
  labels:
    name: gitlab-web
  name: gitlab-web
  annotations:
    loadbalancer: |
      80:
        type: http
        vhost: gitlab.example.com
      443:
        type: http
        vhost: 
        ssl:
          cert: /etc/ssl/certs/wildcard.example.com.crt
          key: /etc/ssl/certs/wildcard.example.com.key
      22:
        type: tcp
        port: 2222
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 80
    - name: ssh
      port: 22
      targetPort: 22
  selector:
    name: gitlab-web
