#
#   Author: Rohith
#   Date: 2015-05-20 23:36:02 +0100 (Wed, 20 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: gitlab-web
spec:
  replicas: 1
  selector:
    name: gitlab-web
  template:
    metadata:
      labels:
        name: gitlab-web
    spec:
      containers:
      - name: gitlab-web
        image: sameersbn/gitlab:latest
        volumeMounts:
          - name: logs
            mountPath: /var/log/gitlab
          - name: data
            mountPath: /home/git/data
        ports:
        - containerPort: 80
        - containerPort: 22
        - containerPort: 443
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 3
        env:
        - name: TERM 
          value: linux
        - name: DEBIAN_FRONTEND
          value: noninteractive
        - name: DB_TYPE
          value: mysql
        - name: DB_HOST
          value: 10.99.243.97
        - name: DB_NAME
          value: gitlabhq
        - name: DB_USER
          value: admin
        - name: DB_PASS
          value: dfdsmfk983w
        - name: REDIS_HOST
          value: 10.99.150.190
        - name: GITLAB_HOST
          value: gitlabs
        - name: REDIS_PORT
          value: "6379"
      volumes:
        - name: data
          rbd: 
            monitors: 
              - 10.250.1.53:6789
              - 10.250.1.54:6789
            pool: rbd
            image: gitlab-data
            user: admin
            keyring: /etc/ceph/ceph.client.admin.keyring
            fsType: xfs
            readOnly: false
        - name: logs
          rbd: 
            monitors: 
              - 10.250.1.53:6789
              - 10.250.1.54:6789
            pool: rbd
            image: gitlab-logs
            user: admin
            keyring: /etc/ceph/ceph.client.admin.keyring
            fsType: xfs
            readOnly: false
      