#
#   Author: Rohith
#   Date: 2015-05-20 23:36:02 +0100 (Wed, 20 May 2015)
#
#  vim:ts=2:sw=2:et
#
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: gitlab-web
spec:
  replicas: 1
  selector:
    name: gitlab-web
  template:
    metadata:
      labels:
        name: gitlab-web
    spec:
      containers:
      - name: gitlab-mysql
        image: tutum/mysql
        volumeMounts:
          - name: mysql
            mountPath: /var/lib/mysql
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_PASS
          value: dfdsmfk983w
      - name: gitlab-web
        image: sameersbn/gitlab:7.13.5
        volumeMounts:
          - name: logs
            mountPath: /var/log/gitlab
          - name: data
            mountPath: /home/git/data
        ports:
        - containerPort: 80
        - containerPort: 22
        - containerPort: 443
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 300
          timeoutSeconds: 3
        env:
        - name: TERM
          value: linux
        - name: DEBIAN_FRONTEND
          value: noninteractive
        - name: DB_TYPE
          value: mysql
        - name: DB_HOST
          value: 127.0.0.1
        - name: DB_NAME
          value: gitlabhq
        - name: DB_USER
          value: admin
        - name: DB_PASS
          value: dfdsmfk983w
        - name: REDIS_HOST
          value: 10.101.1.100
        - name: GITLAB_HOST
          value: gitlab.example.com
        - name: REDIS_PORT
          value: "6379"
        - name: GITLAB_SSH_PORT
          value: "2222"
      volumes:
        - name: data
          rbd:
            monitors:
              - 10.50.10.100:6789
              - 10.50.11.100:6789
              - 10.50.12.100:6789
            pool: rbd
            image: gitlab-data
            user: admin
            secretRef:
              name: ceph-secret
            fsType: xfs
            readOnly: false
        - name: mysql
          rbd:
            monitors:
              - 10.50.10.100:6789
              - 10.50.11.100:6789
              - 10.50.12.100:6789
            pool: rbd
            image: gitlab-mysql
            user: admin
            secretRef:
              name: ceph-secret
            fsType: xfs
            readOnly: false
        - name: logs
          rbd:
            monitors:
              - 10.50.10.100:6789
              - 10.50.11.100:6789
              - 10.50.12.100:6789
            pool: rbd
            image: gitlab-logs
            user: admin
            secretRef:
              name: ceph-secret
            fsType: xfs
            readOnly: false
