#
#   Author: Rohith
#   Date: 2015-05-24 15:48:32 +0100 (Sun, 24 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

apiVersion: v1beta3
kind: Service
metadata:
  labels:
    name: artifactory
  name: artifactory
  annotations:
    loadbalancer: |
      80:
        type: http
        port: 9091
        vhost: artifactory.example.com
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8081
  selector:
    name: artifactory
