#
#   Author: Rohith
#   Date: 2015-06-20 21:40:07 +0100 (Sat, 20 Jun 2015)
#
#  vim:ts=2:sw=2:et
#

apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: elasticsearch-lb
  component: elasticsearch
spec:
  replicas: 1
  selector:
    component: elasticsearch
    role: load-balancer
  template:
    metadata:
      labels:
        name: elasticsearch-lb
        component: elasticsearch
        role: load-balancer
    spec:
      containers:
      - name: elasticsearch-lb
        image: pires/elasticsearch:lb
        ports:
          - name: http
            containerPort: 9200
          - name: transport
            containerPort: 9300
        volumeMounts:
          - name: es-persistent-storage
            mountPath: /data
      volumes:
        - name: es-persistent-storage
          source:
            emptyDir: {}

