#
#   Author: Rohith
#   Date: 2015-06-10 18:19:19 +0100 (Wed, 10 Jun 2015)
#
#  vim:ts=2:sw=2:et
#

apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: jira-web
spec:
  replicas: 1
  selector:
    name: jira-web
  template:
    metadata:
      labels:
        name: jira-web
    spec:
      containers:
      - name: jira-web
        image: cptactionhank/atlassian-jira
        ports:
        - containerPort: 8080
