apiVersion: v1beta3
kind: Service
metadata: 
  labels: 
    name: wordpress
  name: wordpress
spec: 
  ports:
    - port: 9091
      targetPort: 80
  selector: 
    name: wordpress
  type: LoadBalancer
  PublicIPs: [10.250.1.203,10.250.1.204,10.250.1.205]
