#
#   Author: Rohith
#   Date: 2015-05-20 23:36:02 +0100 (Wed, 20 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    name: backend
  template:
    metadata:
      labels:
        name: backend
    spec:
      containers:
      - name: backend
        image: gambol99/apache-php:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 300
          timeoutSeconds: 3
