#
#   Author: Rohith
#   Date: 2015-06-19 16:31:01 +0100 (Fri, 19 Jun 2015)
#
#  vim:ts=2:sw=2:et
#

apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: redis-master
spec:
  replicas: 1
  selector:
    name: redis-master
  template:
    metadata:
      labels:
        name: redis-master
    spec:
      containers:
      - name: redis-master
        image: redis
        ports:
        - containerPort: 6793
