#
#   Author: Rohith
#   Date: 2015-06-19 16:31:08 +0100 (Fri, 19 Jun 2015)
#
#  vim:ts=2:sw=2:et
#

apiVersion: v1beta3
kind: Service
metadata:
  labels:
    name: redis-slave
  name: redis-slave
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis-slave
