#
#   Author: Rohith
#   Date: 2015-06-19 16:31:12 +0100 (Fri, 19 Jun 2015)
#
#  vim:ts=2:sw=2:et
#

apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis-master
  name: redis-master 
  annotations:
    loadbalancer: |
      6379:
        port: 7777
        type: tcp
spec:
  portalIP: 10.101.100.21
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis-master
