#
#   Author: Rohith
#   Date: 2015-05-20 23:35:59 +0100 (Wed, 20 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

apiVersion: v1beta3
kind: Service
metadata:
  labels:
    name: apache
  name: apache
  annotations:
    loadbalancer: |
      80:
        type: http
        port: 9091
        vhost: gitlab.example.com
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: apache
