#
#   Author: Rohith
#   Date: 2015-07-08 13:19:18 +0100 (Wed, 08 Jul 2015)
#
#  vim:ts=2:sw=2:et
#
#
#   Author: Rohith
#   Date: 2015-05-20 23:36:02 +0100 (Wed, 20 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

apiVersion: v1
kind: ReplicationController
metadata:
  name: apache
spec:
  replicas: 3
  selector:
    name: apache
  template:
    metadata:
      labels:
        name: apache
    spec:
      containers:
      - name: apache
        image: gambol99/apache-php:latest
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
          - name: secret-volume
            mountPath: /etc/secret-volume
      volumes:
      - name: secret-volume
        secret:
          secretName: test-secret
