#
#   Author: Rohith
#   Date: 2015-05-20 23:36:09 +0100 (Wed, 20 May 2015)
#
#  vim:ts=2:sw=2:et
#
---

apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: storage
spec:
  replicas: 1
  selector:
    name: storage
  template:
    metadata:
      labels:
        name: storage
    spec:
      containers:
      - name: storage
        image: fedora/apache
        volumeMounts:
          - name: data
            mountPath: /mnt/data
        ports:
        - containerPort: 80
      volumes:
        - name: data
          rbd: 
            monitors: 
              - 10.250.1.53:6789
              - 10.250.1.54:6789
            pool: rbd
            image: storage
            user: admin
            keyring: /etc/ceph/ceph.client.admin.keyring
            fsType: xfs
            readOnly: false

